drop table if exists bookmarks;

create table bookmarks (
  id INTEGER PRIMARY KEY generated by default as identity,
  title VARCHAR(100) NOT NULL, --size?
  "url" TEXT NOT NULL CHECK ("url" LIKE 'https://%.%'),
  rating INTEGER CHECK (rating <= 5 AND rating > 0), --must be 1-5 -> 0 -> error?
  "description" TEXT
);

insert into bookmarks (title, "url", rating, "description")
values 
  ('title1', 'https://www.google.com', 5, 'Search on Google.'),
  ('title2', 'https://www.google.com', 4, 'Search on Google'),
  ('title3', 'https://www.google.com', 3, 'Search on Googl'),
  ('title4', 'https://www.google.com', 2, 'Search on Goog'),
  ('title5', 'https://www.google.com', 1, 'Search on Goo'),
  ('title6', 'https://www.google.com', 2, 'Search on Go'),
  ('title7', 'https://www.google.com', 3, 'Search on G'),
  ('title8', 'https://www.google.com', 4, 'Search on '),
  ('title9', 'https://www.google.com', 5, 'Search on'),
  ('title10', 'https://www.google.com', 1, 'Search o');